import type { AnimMeta } from "../../registry";
import { params } from "./params";

export default {
  name: "Thinking Cube",
  category: "Chat & AI",
  tech: ["React", "CSS 3D", "matrix3d", "Motion"],
  blurb: "An agent 'thinking' state: a Rubik's cube assembles from its core, then solves its own scramble.",
  source: "Desktop/card animation/src/components/thinking-cube",
  behavior: { trigger: "sequence", frequency: "frequent" },
  reducedMotion: "none",
  reducedMotionNote: "Only the label shimmer stops; the 20s spin, piece spawns and layer turns keep moving.",
  deps: ["react", "motion", "lucide-react"],
  load: () => import("./index"),
  params,
  schema: {
    loop: { type: "boolean", label: "Loop", group: "Demo" },
    restMs: { type: "number", label: "Rest before replay", group: "Demo", min: 0, max: 6000, step: 100, unit: "ms" },
    seed: { type: "number", label: "Scramble seed", group: "Demo", min: 1, max: 99 },
    moves: { type: "number", label: "Solve moves", group: "Solve", min: 2, max: 30 },
    coreHoldMs: { type: "number", label: "Core hold", group: "Assemble", min: 0, max: 4000, step: 50, unit: "ms" },
    spawnMs: { type: "number", label: "Piece travel", group: "Assemble", min: 100, max: 1500, step: 10, unit: "ms" },
    staggerMs: { type: "number", label: "Piece stagger", group: "Assemble", min: 0, max: 400, step: 5, unit: "ms", role: "stagger" },
    settleMs: { type: "number", label: "Settle", group: "Assemble", min: 0, max: 3000, step: 50, unit: "ms" },
    turnMs: { type: "number", label: "Layer turn", group: "Solve", min: 80, max: 1500, step: 10, unit: "ms" },
    turnGapMs: { type: "number", label: "Gap between turns", group: "Solve", min: 0, max: 1000, step: 10, unit: "ms" },
    turnEase: { type: "easing", label: "Turn easing", group: "Solve" },
    spinSeconds: { type: "number", label: "Idle spin period", group: "Look", min: 2, max: 60, unit: "s" },
    tilt: { type: "number", label: "Tilt", group: "Look", min: -60, max: 60, unit: "°" },
    cell: { type: "number", label: "Piece spacing", group: "Look", min: 20, max: 48, unit: "px" },
    seam: { type: "number", label: "Seam", group: "Look", min: 0, max: 12, unit: "px" },
    inner: { type: "color", label: "Plastic", group: "Color" },
    right: { type: "color", label: "Right face", group: "Color" },
    left: { type: "color", label: "Left face", group: "Color" },
    up: { type: "color", label: "Up face", group: "Color" },
    down: { type: "color", label: "Down face", group: "Color" },
    front: { type: "color", label: "Front face", group: "Color" },
    back: { type: "color", label: "Back face", group: "Color" },
  },
} satisfies Omit<AnimMeta, "id">;
