import type { AnimMeta } from "../../registry";
import { params } from "./params";

export default {
  name: "Chat Quiz",
  poster: { at: 2600, y: 0.45 },
  category: "Chat & AI",
  tech: ["React", "Motion", "Canvas 2D", "Springs", "Layout animation"],
  blurb: "An AI composer that interviews you before it helps — card-to-pill morph over a spring-lattice dither field.",
  source: "Desktop/portfolio v2/src/components/animations/chat-quiz (from animation-portfoliov2)",
  behavior: { trigger: "state", frequency: "frequent" },
  reducedMotion: "full",
  reducedMotionNote: "MotionConfig reducedMotion=\"user\" drops transform and layout animation, the shimmer stops, and the dither lattice keeps its colour but loses every displacement.",
  keyboard: "Typing / or @ animates the command palette open (rise + scale).",
  ui: true,
  deps: ["react", "react-dom", "motion", "lucide-react"],
  load: () => import("./index"),
  params,
  schema: {
    autoplay: { type: "boolean", label: "Autoplay demo", group: "Demo", hint: "Types a command, answers the quiz and thinks — on a loop." },
    loopMs: { type: "number", label: "Loop every", group: "Demo", min: 8000, max: 30000, step: 500, unit: "ms" },
    beatMs: { type: "number", label: "Thinking beat", group: "Timing", min: 200, max: 2000, step: 10, unit: "ms", hint: "Time per sub-step while it thinks." },
    staggerMs: { type: "number", label: "Option stagger", group: "Timing", min: 0, max: 200, unit: "ms", role: "stagger" },
    rowEnterMs: { type: "number", label: "Option enter", group: "Timing", min: 100, max: 1200, step: 10, unit: "ms", role: "enter" },
    rowExitMs: { type: "number", label: "Option exit", group: "Timing", min: 60, max: 800, step: 10, unit: "ms", role: "exit" },
    easeOut: { type: "easing", label: "Entrance curve", group: "Timing", role: "enter" },
    easeIn: { type: "easing", label: "Exit curve", group: "Timing", role: "exit" },
    morphStiffness: { type: "number", label: "Card ↔ pill stiffness", group: "Springs", min: 50, max: 800 },
    morphDamping: { type: "number", label: "Card ↔ pill damping", group: "Springs", min: 5, max: 80 },
    slideStiffness: { type: "number", label: "Highlight slide stiffness", group: "Springs", min: 50, max: 900 },
    slideDamping: { type: "number", label: "Highlight slide damping", group: "Springs", min: 5, max: 80 },
    snapStiffness: { type: "number", label: "Press snap stiffness", group: "Springs", min: 100, max: 1200 },
    snapDamping: { type: "number", label: "Press snap damping", group: "Springs", min: 5, max: 80 },
    submit: { type: "color", label: "Submit button", group: "Color" },
    stage1: { type: "color", label: "Thinking stage 1", group: "Color" },
    stage2: { type: "color", label: "Thinking stage 2", group: "Color" },
    stage3: { type: "color", label: "Thinking stage 3", group: "Color" },
    fieldDeep: { type: "color", label: "Lattice deep (Build mode)", group: "Color" },
    fieldBright: { type: "color", label: "Lattice bright (Build mode)", group: "Color" },
    cell: { type: "number", label: "Lattice spacing", group: "Dither lattice", min: 4, max: 16, step: 0.5, unit: "px", reload: true, hint: "Dot count grows with 1/spacing² — the canvas cost lever." },
    dot: { type: "number", label: "Dot radius", group: "Dither lattice", min: 0.5, max: 4, step: 0.1, unit: "px" },
    spring: { type: "number", label: "Spring K", group: "Dither lattice", min: 0.02, max: 0.4, step: 0.01 },
    damping: { type: "number", label: "Damping", group: "Dither lattice", min: 0.5, max: 0.98, step: 0.01 },
    push: { type: "number", label: "Cursor push", group: "Dither lattice", min: 0, max: 8, step: 0.1 },
    waveSpeed: { type: "number", label: "Shockwave speed", group: "Dither lattice", min: 0.1, max: 2, step: 0.02, unit: "px/ms" },
  },
} satisfies Omit<AnimMeta, "id">;
