import type { AnimMeta } from "../../registry";

export default {
  name: "Coins & Notes",
  poster: { at: 1800, y: 0.5 },
  category: "Shaders & GPU",
  tech: ["Three.js", "WebGL", "GLSL", "vgpu", "WGSL", "Bloom"],
  blurb: "Struck coins and printed banknotes with six shader looks: prism, holo, mint, topo, X-ray and a UV torch.",
  source: "Desktop/experiment animation/motiscope-output/webgl/index.html",
  behavior: { trigger: "interaction", frequency: "rare" },
  reducedMotion: "partial",
  reducedMotionNote:
    "Time freezes, the spin spring snaps, folds land instantly and the idle demo stops — but the render loop keeps drawing the still scene at full rate.",
  html: true,
  layout: "fill",
  params: {
    mode: "Prism",
    item: "US Dollar coin",
    tint: "#ffffff",
    iridescence: 1,
    bloom: 1,
    exposure: 0.95,
    flutter: 1,
    carouselMs: 870,
    carouselEase: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    spinStiffness: 90,
    spinDamping: 11,
    foldStagger: 512,
    idleDemoMs: 7000,
    dprCap: 2,
  },
  schema: {
    mode: { type: "select", label: "Shader", group: "Shader", options: ["Prism", "Holo", "Mint", "Topo", "X-ray", "UV"] },
    item: { type: "select", label: "Showing", group: "Shader", options: ["US Dollar coin", "₹1 coin", "₹10 coin", "開元通寶 coin", "¥1 coin", "¥100 coin", "US $100 note", "¥100 note", "₹500 note", "¥1000 note"] },
    tint: { type: "color", label: "Metal tint", group: "Color", hint: "Multiplies every coin's base metal colour." },
    iridescence: { type: "number", label: "Iridescence", group: "Color", min: 0, max: 2.5, step: 0.05 },
    bloom: { type: "number", label: "Bloom", group: "Color", min: 0, max: 3, step: 0.05 },
    exposure: { type: "number", label: "Exposure", group: "Color", min: 0.4, max: 1.6, step: 0.01 },
    flutter: { type: "number", label: "Note flutter", group: "Motion", min: 0, max: 3, step: 0.05 },
    carouselMs: { type: "number", label: "Carousel slide", group: "Motion", min: 150, max: 1600, step: 10, unit: "ms" },
    carouselEase: { type: "easing", label: "Carousel easing", group: "Motion" },
    spinStiffness: { type: "number", label: "Spin stiffness", group: "Motion", min: 20, max: 300 },
    spinDamping: { type: "number", label: "Spin damping", group: "Motion", min: 2, max: 40 },
    foldStagger: { type: "number", label: "Fold stagger", group: "Motion", min: 0, max: 1000, step: 10, unit: "ms", hint: "Delay between a note's three creases." },
    idleDemoMs: { type: "number", label: "Idle demo after", group: "Motion", min: 0, max: 20000, step: 500, unit: "ms", hint: "0 turns the self-playing flip/fold off." },
    dprCap: { type: "number", label: "Pixel ratio cap", group: "Performance", min: 0.5, max: 3, step: 0.25, role: "dpr", hint: "Fill rate scales with the square of this — the biggest GPU lever." },
  },
} satisfies Omit<AnimMeta, "id">;
